.TH "gaia Directory Reference" 3 "Tue Jul 7 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBaddon\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgaia\&.c\fP"
.br
.ti -1c
.RI "file \fBgaia\&.h\fP"
.br
.in -1c
