.TH "client_network_func_t" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client_network_func_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBgaia_addon_func_t\fP \fBbasic\fP"
.br
.ti -1c
.RI "int(* \fBreceive_message\fP )(struct \fBgaia_message_t\fP *msg)"
.br
.ti -1c
.RI "int(* \fBsend_message\fP )(struct \fBgaia_message_t\fP *msg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
