.TH "client_t" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "char \fBip\fP [16]"
.br
.ti -1c
.RI "int \fBrecv_size\fP"
.br
.ti -1c
.RI "char \fBrecv_buff\fP [BUFF_SIZE]"
.br
.ti -1c
.RI "char \fBsend_buff\fP [BUFF_SIZE]"
.br
.ti -1c
.RI "pthread_mutex_t \fBnetwork_lock\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
