.TH "config.h" 3 "Thu Jul 2 2015" "Version 0.9.0" "gaia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <gaia/gaia\&.h>\fP
.br
\fC#include <gaia/addon/addon\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBconfig_func_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBCONFIG_FLAG_LOAD_ADDON\fP = 0x00000001, \fBCONFIG_FLAG_RUN_AS_SERVER\fP = 0x00000002 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for gaia from the source code\&.
