.TH "config_func_t" 3 "Tue Jul 7 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_func_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <direct_config\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBgaia_addon_func_t\fP \fBbasic\fP"
.br
.ti -1c
.RI "int(* \fBcheck_flag\fP )(int flag)"
.br
.ti -1c
.RI "const char **(* \fBget_addon_list\fP )()"
.br
.ti -1c
.RI "unsigned int(* \fBget_server_port\fP )()"
.br
.ti -1c
.RI "int(* \fBget_server_max_conns\fP )()"
.br
.ti -1c
.RI "const char *(* \fBremote_server_hostname\fP )()"
.br
.ti -1c
.RI "const char *(* \fBremote_server_service\fP )()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Get config information from config center like this\&.
.PP
Example: 
.PP
.nf
struct config_func_t *config;
const char **file_list;

config = (struct config_func_t *)func->get_addon_by_type(ADDON_TYPE_CONFIG);

if (config->check_flag(CONFIG_FLAG_LOAD_ADDON)) {
    file_list = config->get_addon_list();
    while (*file_list) {
        printf("load addon : %s\n", *file_list++);
    }
}

if (config->check_flag(CONFIG_FLAG_RUN_AS_SERVER)) {
    printf("local server listen port : %d\n", config->get_server_port());
    printf("local server maximum connections : %d\n", config->get_server_max_conns());
}

printf("remote server(%s:%s)\n", config->remote_server_hostname(),
    config->remote_server_service());

.fi
.PP
 
.SH "Field Documentation"
.PP 
.SS "struct \fBgaia_addon_func_t\fP config_func_t::basic"
Basic\&. 
.SS "int(* config_func_t::check_flag) (int flag)"
Check if flag marked\&. 
.SS "const char**(* config_func_t::get_addon_list) ()"
Use this interface to get addon list\&. 
.SS "unsigned int(* config_func_t::get_server_port) ()"
Get local server listen port\&. 
.SS "int(* config_func_t::get_server_max_conns) ()"
Get local server maximum connections\&. 
.SS "const char*(* config_func_t::remote_server_hostname) ()"
Get remote server host name\&. 
.SS "const char*(* config_func_t::remote_server_service) ()"
Get remote server service name\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
