.TH "direct_config.c" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
direct_config.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <gaia/addon/config/direct_config\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADDON_ID_DIRECT_CONFIG\fP   0x10000032002"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBgaia_addon_t\fP * \fBdirect_config_info\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADDON_ID_DIRECT_CONFIG   0x10000032002"
Direct config add-on id\&. 
.SH "Function Documentation"
.PP 
.SS "struct \fBgaia_addon_t\fP* direct_config_info ()"
Return direct config add-on information\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
