.TH "direct_loader.h" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
direct_loader.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <gaia/addon/addon\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBloader_func_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBgaia_addon_t\fP * \fBdirect_loader_info\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBgaia_addon_t\fP* direct_loader_info ()"
Direct loader add-on information\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
