.TH "direct_loader.c" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
direct_loader.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <gaia/addon/loader/direct_loader\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADDON_ID_DIRECT_LOADER\fP   0x100000000002222"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBgaia_addon_t\fP * \fBdirect_loader_info\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADDON_ID_DIRECT_LOADER   0x100000000002222"
Direct config add-on id\&. 
.SH "Function Documentation"
.PP 
.SS "struct \fBgaia_addon_t\fP* direct_loader_info ()"
Direct loader add-on information\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
