.TH "direct_config.h" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
direct_config.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <gaia/addon/addon\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBconfig_func_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBconfig_flag\fP { \fBCONFIG_FLAG_LOAD_ADDON\fP = 0x00000001, \fBCONFIG_FLAG_USE_NETWORK\fP = 0x00000002, \fBCONFIG_FLAG_USE_SHELL\fP = 0x00000003, \fBCONFIG_FLAG_RUN_AS_SERVER\fP = 0x00000010 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBgaia_addon_t\fP * \fBdirect_config_info\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Direct config add-on\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBconfig_flag\fP"
Config flag\&. 
.SH "Function Documentation"
.PP 
.SS "struct \fBgaia_addon_t\fP* direct_config_info ()"
Return direct config add-on information\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
