.TH "gaia_context_t" 3 "Tue Jul 7 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia_context_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu1\fP \fBworking\fP"
.br
.ti -1c
.RI "pthread_rwlock_t \fBaddon_lock\fP"
.br
.ti -1c
.RI "struct \fBlinked_list\fP \fBaddon_list\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBmessage_lock\fP"
.br
.ti -1c
.RI "struct \fBlinked_list\fP \fBmessage_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
context 

.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
