.TH "gaia_message_list_t" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia_message_list_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBlinked_list\fP \fBlist\fP"
.br
.ti -1c
.RI "struct \fBgaia_message_t\fP \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Message list entry\&. Used by GAIA global context\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBlinked_list\fP gaia_message_list_t::list"
List head of message list\&. 
.SS "struct \fBgaia_message_t\fP gaia_message_list_t::message"
Message\&.
.PP
\fBSee also:\fP
.RS 4
\fBgaia_message_t\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
