.TH "gaia.h" 3 "Thu Jul 2 2015" "Version 0.9.0" "gaia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/util\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgaia_message_t\fP"
.br
.ti -1c
.RI "struct \fBgaia_func_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgaia_start_up\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void gaia_start_up (void)"
start gaia everything become nice
.PP
always handle message after gaia start up 
.SH "Author"
.PP 
Generated automatically by Doxygen for gaia from the source code\&.
