.TH "gaia_addon_func_t" 3 "Tue Jul 7 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia_addon_func_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <addon\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBinit\fP )(struct \fBgaia_func_t\fP *func)"
.br
.ti -1c
.RI "void(* \fBexit\fP )(struct \fBgaia_addon_t\fP *addon)"
.br
.ti -1c
.RI "void(* \fBhandle_message\fP )(struct \fBgaia_message_t\fP *msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Add-on functions set\&. 
.SH "Field Documentation"
.PP 
.SS "int(* gaia_addon_func_t::init) (struct \fBgaia_func_t\fP *func)"
Initialize add-on\&. Call after install\&. 
.SS "void(* gaia_addon_func_t::exit) (struct \fBgaia_addon_t\fP *addon)"
Cleanup add-on\&. Call before uninstall\&. 
.SS "void(* gaia_addon_func_t::handle_message) (struct \fBgaia_message_t\fP *msg)"
Handle message\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
