.TH "gaia.h" 3 "Tue Jul 7 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/util\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgaia_message_t\fP"
.br
.ti -1c
.RI "struct \fBgaia_func_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgaia_running\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void gaia_running ()"
Method to run GAIA\&. Never stop until a quit message received\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
