.TH "gaia_addon_func_t" 3 "Thu Jul 2 2015" "Version 0.9.0" "gaia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia_addon_func_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBinit\fP )(struct \fBgaia_func_t\fP *func)"
.br
.ti -1c
.RI "void(* \fBexit\fP )(struct \fBgaia_addon_t\fP *addon)"
.br
.ti -1c
.RI "void(* \fBhandle_message\fP )(struct \fBgaia_message_t\fP *msg)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gaia from the source code\&.
