.TH "gaia_context_t" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia_context_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu1\fP \fBworking\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "pthread_rwlock_t \fBaddon_lock\fP"
.br
.ti -1c
.RI "struct \fBlinked_list\fP \fBaddon_list\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBmessage_lock\fP"
.br
.ti -1c
.RI "struct \fBlinked_list\fP \fBmessage_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
GAIA running context\&. 
.SH "Field Documentation"
.PP 
.SS "\fBu1\fP gaia_context_t::working"
Working flag\&. Exit if set false\&. 
.SS "int gaia_context_t::index"
Last add-on index\&. 
.SS "pthread_rwlock_t gaia_context_t::addon_lock"
Read-write lock for add-on list \&. 
.SS "struct \fBlinked_list\fP gaia_context_t::addon_list"
Add-on list\&. 
.SS "pthread_mutex_t gaia_context_t::message_lock"
Lock for message list\&. 
.SS "struct \fBlinked_list\fP gaia_context_t::message_list"
Message list\&.
.PP
\fBTodo\fP
.RS 4
use cache 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
