.TH "gaia_addon_t" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia_addon_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <addon\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBid\fP"
.br
.ti -1c
.RI "\fBu4\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBu4\fP \fBversion\fP"
.br
.ti -1c
.RI "\fBu4\fP \fBfunc_size\fP"
.br
.ti -1c
.RI "struct \fBgaia_addon_func_t\fP * \fBfunc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Add-on information\&. 
.SH "Field Documentation"
.PP 
.SS "\fBu8\fP gaia_addon_t::id"
Add-on id\&. 
.SS "\fBu4\fP gaia_addon_t::type"
Add-on type\&. 
.SS "\fBu4\fP gaia_addon_t::version"
Add-on version\&. 
.SS "\fBu4\fP gaia_addon_t::func_size"
Functions set size\&. 
.SS "struct \fBgaia_addon_func_t\fP* gaia_addon_t::func"
Pointer to functions set\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
