.TH "gaia_message_list_t" 3 "Thu Jul 2 2015" "Version 0.9.0" "gaia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia_message_list_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct linked_list \fBlist\fP"
.br
.ti -1c
.RI "struct \fBgaia_message_t\fP \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
message list entry 

.SH "Author"
.PP 
Generated automatically by Doxygen for gaia from the source code\&.
