.TH "gaia_addon_info_t" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia_addon_info_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "struct \fBgaia_func_t\fP \fBfunc\fP"
.br
.ti -1c
.RI "struct \fBgaia_addon_info_t\fP * \fBparent\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBlist_lock\fP"
.br
.ti -1c
.RI "struct \fBlinked_list\fP \fBson_list\fP"
.br
.ti -1c
.RI "struct \fBlinked_list\fP \fBbro_list\fP"
.br
.ti -1c
.RI "struct \fBlinked_list\fP \fBaddon_list\fP"
.br
.ti -1c
.RI "struct \fBgaia_addon_t\fP \fBaddon_info\fP"
.br
.ti -1c
.RI "struct \fBgaia_addon_t\fP * \fBaddon_orig\fP"
.br
.ti -1c
.RI "struct \fBgaia_addon_func_t\fP * \fBaddon_func\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Add-on information\&. 
.SH "Field Documentation"
.PP 
.SS "int gaia_addon_info_t::index"
Add-on index\&. 
.SS "struct \fBgaia_func_t\fP gaia_addon_info_t::func"
Function sets\&. Each add-on has a private sets\&.
.PP
\fBSee also:\fP
.RS 4
\fBgaia_func_t\fP 
.RE
.PP

.SS "struct \fBgaia_addon_info_t\fP* gaia_addon_info_t::parent"
Pointer to parent add-on\&. 
.SS "pthread_mutex_t gaia_addon_info_t::list_lock"
Son list lock\&. 
.SS "struct \fBlinked_list\fP gaia_addon_info_t::son_list"
Son list\&. 
.SS "struct \fBlinked_list\fP gaia_addon_info_t::bro_list"
All add-ons has same parent linked as a list\&. 
.SS "struct \fBlinked_list\fP gaia_addon_info_t::addon_list"
All add-ons linked as a list\&. 
.SS "struct \fBgaia_addon_t\fP gaia_addon_info_t::addon_info"
Add-on information for reader\&.
.PP
\fBSee also:\fP
.RS 4
\fBgaia_addon_t\fP 
.RE
.PP

.SS "struct \fBgaia_addon_t\fP* gaia_addon_info_t::addon_orig"
Original add-on information\&.
.PP
\fBSee also:\fP
.RS 4
\fBgaia_addon_t\fP 
.RE
.PP

.SS "struct \fBgaia_addon_func_t\fP* gaia_addon_info_t::addon_func"
Function table of add-on\&.
.PP
Example: 
.PP
.nf
struct config_func_t {
  struct gaia_addon_func_t basic;
  int (*check_flag)(int flag);
  \&.\&.\&.
};

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
