.TH "gaia_addon_t" 3 "Thu Jul 2 2015" "Version 0.9.0" "gaia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gaia_addon_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u8 \fBid\fP"
.br
.ti -1c
.RI "u4 \fBtype\fP"
.br
.ti -1c
.RI "u4 \fBversion\fP"
.br
.ti -1c
.RI "u4 \fBfunc_size\fP"
.br
.ti -1c
.RI "struct \fBgaia_addon_func_t\fP * \fBfunc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gaia from the source code\&.
