.TH "linked_list" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linked_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBlinked_list\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBlinked_list\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Element of linked list must contain two pointers (previous, next)\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBlinked_list\fP* linked_list::prev"
Previous and next node\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
