.TH "local_config_func_t" 3 "Thu Jul 2 2015" "Version 0.9.0" "gaia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
local_config_func_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBgaia_addon_func_t\fP \fBbasic\fP"
.br
.ti -1c
.RI "const char **(* \fBget_addon_list\fP )()"
.br
.ti -1c
.RI "int(* \fBrun_as_server\fP )()"
.br
.ti -1c
.RI "unsigned int(* \fBserver_port\fP )()"
.br
.ti -1c
.RI "int(* \fBserver_max_conns\fP )()"
.br
.ti -1c
.RI "const char *(* \fBserver_hostname\fP )()"
.br
.ti -1c
.RI "const char *(* \fBserver_service\fP )()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for gaia from the source code\&.
