.TH "simple_network.c" 3 "Tue Jul 14 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simple_network.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <gaia/addon/network/simple_network\&.h>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBADDON_ID_SIMPLE_NETWORK\fP = 0x20000032100002 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBgaia_addon_t\fP * \fBsimple_network_info\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
