.TH "util.h" 3 "Tue Jul 7 2015" "Version 1.0.0" "GAIA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
util.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <endian\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBu1\fP"
.br
.ti -1c
.RI "typedef uint16_t \fBu2\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBu4\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBu8\fP"
.br
.ti -1c
.RI "typedef int8_t \fBs1\fP"
.br
.ti -1c
.RI "typedef int16_t \fBs2\fP"
.br
.ti -1c
.RI "typedef int32_t \fBs4\fP"
.br
.ti -1c
.RI "typedef int64_t \fBs8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
u1,u2,u4,u8 is short for unsigned integer\&.
.PP
s1,s2,s4,s8 is short for signed integer\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef uint8_t \fBu1\fP"
Short for 8-bit unsigned integer\&. 
.SS "typedef uint16_t \fBu2\fP"
Short for 16-bit unsigned integer\&. 
.SS "typedef uint32_t \fBu4\fP"
Short for 32-bit unsigned integer\&. 
.SS "typedef uint64_t \fBu8\fP"
Short for 64-bit unsigned integer\&. 
.SS "typedef int8_t \fBs1\fP"
Short for 8-bit signed integer\&. 
.SS "typedef int16_t \fBs2\fP"
Short for 16-bit signed integer\&. 
.SS "typedef int32_t \fBs4\fP"
Short for 32-bit signed integer\&. 
.SS "typedef int64_t \fBs8\fP"
Short for 64-bit signed integer\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for GAIA from the source code\&.
